### ISSUE TITLE
Fix 32 bit raspberry pi builds

### ISSUE THREAD

**Issue by spuder** [spuder/yeet#1]
The rasbperry pi builds broke the darwin/amd64 builds because of an erronious `goarm` variable

https://github.com/spuder/yeet/actions/runs/1473635311

```
# .github/workflows/release.yaml

on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/arm, linux/arm64, linux/amd64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        include:
          - goarch: arm
            goos: linux
            goarm: 5
        exclude:  
          - goarch: "386"
            goos: darwin 
          - goarch: "arm64"
            goos: windows
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.21
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goarm: ${{ matrix.goarm }}
        # goversion: "https://dl.google.com/go/go1.17.2.linux-amd64.tar.gz"
        # project_path: "./"
        binary_name: "yeet"
        # extra_files: LICENSE.txt README.md
 ```
 
 https://www.thepolyglotdeveloper.com/2017/04/cross-compiling-golang-applications-raspberry-pi/
